name: Render LaTeX

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra imagemagick
        pip install -r requirements.txt

    - name: Verify ImageMagick installation
      run: magick --version

    - name: Run render_latex.py
      run: python scripts/render_latex.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add resume.pdf resume.png
        git commit -m 'Add rendered PDF and PNG'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}